# Generated by Django 5.1.3 on 2024-12-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='old_cart',
        ),
    ]
